


services:
  web:
    container_name: proxy
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ./config/revers_proxy.conf:/etc/nginx/conf.d/revers_proxy.conf
    ports:
      - "8080:80" 
      - "8081:8081" 
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
      - universal
  api:
    container_name: api
    image: node
    # ports:
    #   - "3000:3000"
    volumes:
      - ../ts_express:/app
    working_dir: /app
    command: npm run dev
    networks:
      - universal

networks:
  universal: 
    driver: bridge